require("plugins.setup")
require("plugins.dressing")
require("plugins.telescope")
require("plugins.nvim-tree")
require("plugins.comments")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.toggleterm")
require("plugins.trouble")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.inc-rename")
require("plugins.formatter")
require("plugins.autopairs")
require("plugins.venv-selector")
require("plugins.neodev")
require("plugins.neotest")
require("plugins.gitsigns")
require("plugins.colorscheme")
require("plugins.dap")
require("plugins.fold")
require("plugins.copilot-chat")
require("plugins.harpoon")
require("plugins.vimade")
require("plugins.quicknote")
require("plugins.neoai")
-- require("plugins.refactoring")
-- require("plugins.aider")
-- require("plugins.avante")
