-- local M = {}
--
-- local config = require("nvim_aider.config")
-- local snacks = require("snacks.terminal")
--
-- require("nvim_aider").setup({
-- 	-- args = {
-- 	-- 	"--no-auto-commits",
-- 	-- 	"--pretty",
-- 	-- 	"--stream",
-- 	-- },
-- })
--
-- local function create_cmd(opts)
-- 	local cmd = "make aa"
--
-- 	return cmd
-- end
--
-- function M.toggle(opts)
-- 	opts = vim.tbl_deep_extend("force", config.options, opts or {})
--
-- 	local cmd = create_cmd(opts)
-- 	return snacks.toggle(cmd, opts)
-- end
--
-- return M
