# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Make sure to use virtualenv
export PIP_REQUIRE_VIRTUALENV=true

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"

# why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_CD

# GCP
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

# Naver search

# openai

# langchain
LANGCHAIN_TRACING_V2=true


#####################
####### alias #######
#####################

alias python="python3"

# [vi]
alias v="nvim ."
alias vi=nvim
alias vim=nvim

# [ls]
alias ll='ls -al'

# [tmux]
alias t='tmux'
alias mux='tmuxinator'

# [settings files]
alias alacrittyconf='nvim ~/.config/alacritty/alacritty.toml'
alias preztoconf='nvim ~/.zprezto/runcoms/zshrc'
alias preztorc='nvim ~/.zprezto/runcoms/zpreztorc'
alias zshrc='nvim ~/.zshrc'
alias tmuxconf='nvim ~/.tmux.conf'

# etc
alias c='clear'
alias jn="jupyter notebook"

# docker & k8s
# check first prezto module
alias mk='minikube'
alias k='kubectl'
alias h='helm'
alias mkon='source ~/minikube_docker.sh on'
alias mkoff='source ~/minikube_docker.sh off'

# terraform
alias tf='terraform'

# github copilot cli
alias '??'='gh copilot suggest -t shell'
